export { default as About } from './about'
export { default as Contact} from './contact'
export { default as Experience} from './experience'
export { default as Projects} from './projects'
export { default as Hero} from './Hero'